"""Base.metadata gives every constraint a deterministic name.

Without this, Alembic's SQLite "batch mode" (the only way SQLite can add a
foreign key to an existing table -- see migrations/env.py's
render_as_batch=True) raises ``ValueError: Constraint must have a name`` on
an autogenerated, unnamed foreign key. This is a static check against
Base.metadata itself rather than a full Alembic autogenerate run, which
would need a real on-disk SQLite file and two migration passes to exercise.
"""

from sqlalchemy import ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column

from zeython.db import Model


class NamingConventionAuthor(Model):
    __tablename__ = "naming_convention_authors"

    name: Mapped[str] = mapped_column(String(255))


class NamingConventionBook(Model):
    __tablename__ = "naming_convention_books"

    title: Mapped[str] = mapped_column(String(255))
    author_id: Mapped[int] = mapped_column(ForeignKey("naming_convention_authors.id"))


def test_foreign_key_constraints_get_a_deterministic_name() -> None:
    table = NamingConventionBook.__table__
    foreign_keys = list(table.foreign_key_constraints)

    assert len(foreign_keys) == 1
    assert foreign_keys[0].name == "fk_naming_convention_books_author_id_naming_convention_authors"


def test_primary_key_constraints_get_a_deterministic_name() -> None:
    table = NamingConventionAuthor.__table__

    assert table.primary_key.name == "pk_naming_convention_authors"
